package testcases;

import common.Constant;
import org.openqa.selenium.By;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.testng.Assert;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import pageobjects.PurchaseInvoiceCreatePage;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Test Suite: Tạo hóa đơn nhập hàng
 * Luồng: Đăng nhập → Trang chủ → Click "Nhập hàng" → Click "Thêm hóa đơn nhập"
 *
 * Chiến lược dữ liệu: KHÔNG hardcode tên/SĐT cụ thể.
 * Thay vào đó, đọc động từ dropdown để test ổn định lâu dài.
 *
 * TC_01 – Mã HDN tự động sinh, không chỉnh sửa được
 * TC_02 – Thêm hóa đơn nhập thành công
 * TC_03 – Tìm kiếm NCC theo tên – có kết quả
 * TC_04 – Tìm kiếm NCC theo SĐT – có kết quả
 * TC_05 – Tìm kiếm NCC – không có kết quả
 */
public class PurchaseInvoiceCreateTest extends BaseTest {

    // Từ khóa chắc chắn không tồn tại trong bất kỳ DB nào
    private static final String NON_EXISTING_SUPPLIER = "XYZ_NCC_KHONG_TON_TAI_999";

    private PurchaseInvoiceCreatePage page;

    // ===================== SETUP =====================

    @BeforeMethod
    @Override
    public void setUp() {
        super.setUp();
        page = new PurchaseInvoiceCreatePage(driver, wait);

        // Bước 1: Đăng nhập
        login();

        // Bước 2: Click menu "Nhập hàng"
        By nhapHangMenu = By.xpath("//nav//a[.//span[text()='Nhập hàng']]");
        wait.until(ExpectedConditions.elementToBeClickable(nhapHangMenu)).click();
        sleep(800);

        // Bước 3: Click nút "Thêm hóa đơn nhập"
        By themHoaDonBtn = By.xpath("//button[contains(@class,'btn-add')]");
        wait.until(ExpectedConditions.elementToBeClickable(themHoaDonBtn)).click();
        sleep(1000);
    }

    // ===================== TEST CASES =====================

    /**
     * TC_01 – Mã HDN tự động sinh, không chỉnh sửa được
     */
    @Test(description = "TC_01 - Mã HDN tự động sinh, không chỉnh sửa được")
    public void TC_01_InvoiceCodeAutoGeneratedAndReadonly() {
        System.out.println("=== TC_01: Mã HDN tự động sinh, không chỉnh sửa được ===");

        Assert.assertTrue(page.isAt(), "[FAIL] Không hiển thị trang Thêm mới đơn nhập");

        String autoCode = page.getInvoiceCode();
        System.out.println("  → Mã HDN tự động sinh: " + autoCode);

        Assert.assertFalse(autoCode == null || autoCode.trim().isEmpty(),
            "[FAIL] Trường Mã HDN bị rỗng – hệ thống chưa tự động sinh mã");

        Assert.assertTrue(page.isInvoiceCodeReadonly(),
            "[FAIL] Trường Mã HDN không có thuộc tính readonly");

        System.out.println("✓ TC_01 PASS: Mã HDN = '" + autoCode + "', readonly = true");
    }

    /**
     * TC_02 – Thêm hóa đơn nhập thành công
     *
     * Không hardcode tên NCC/SP – lấy item đầu tiên từ dropdown.
     */
    @Test(description = "TC_02 - Thêm hóa đơn nhập thành công")
    public void TC_02_AddPurchaseInvoiceSuccess() {
        System.out.println("=== TC_02: Thêm hóa đơn nhập thành công ===");

        Assert.assertTrue(page.isAt(), "[FAIL] Không hiển thị trang Thêm mới đơn nhập");

        // Bước 1: Nhập ngày nhập = ngày giờ hiện tại
        // datetime-local input nhận yyyy-MM-ddTHH:mm, Django parse_datetime cần giây
        // → dùng JS set value để đảm bảo format đúng
        String now = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm"));
        page.enterImportDate(now);
        System.out.println("  → Ngày nhập: " + now);
        System.out.println("  → [CHECK] ngayNhap value: " + page.getImportDate());

        // Bước 2: Mở dropdown NCC (click vào ô → onfocus → showAllNCC), chọn NCC đầu tiên
        page.openSupplierDropdown();
        Assert.assertTrue(page.isSupplierDropdownVisible(),
            "[FAIL] Dropdown NCC không hiển thị – DB có thể không có NCC active");
        page.selectFirstSupplierFromDropdown();
        Assert.assertTrue(page.isSupplierSelected(),
            "[FAIL] NCC chưa được chọn (card không hiển thị)");
        System.out.println("  → Đã chọn NCC đầu tiên trong danh sách");

        // Bước 3: Mở dropdown SP, chọn SP đầu tiên
        page.openProductDropdown();
        page.selectFirstProductFromDropdown();
        sleep(500);
        System.out.println("  → Đã chọn sản phẩm đầu tiên trong danh sách");

        // Bước 4: Nhập số lượng=5, đơn giá=100000, chiết khấu=0
        page.setProductQuantity(0, "5");
        page.setProductDonGia(0, "100000");
        page.setProductChietKhau(0, "0");
        System.out.println("  → Số lượng=5, Đơn giá=100.000, Chiết khấu=0");

        // Bước 5: Debug trước khi submit
        System.out.println("  → [PRE-SUBMIT] sanPhamJson: " + page.getSanPhamJson());
        System.out.println("  → [PRE-SUBMIT] nccId: " + page.getNccId());
        System.out.println("  → [PRE-SUBMIT] tongTien: " + page.getTongTienInput());

        // Nhấn "Thêm"
        page.clickSubmit();

        // Debug: in giá trị hidden inputs và URL sau submit
        String currentUrl = page.getCurrentUrl();
        System.out.println("  → URL sau submit: " + currentUrl);
        System.out.println("  → sanPhamJson: " + page.getSanPhamJson());
        System.out.println("  → nccId: " + page.getNccId());

        // Kết quả: redirect về /nhap-hang/ (không còn /them/)
        Assert.assertTrue(
            currentUrl.contains("/nhap-hang/") && !currentUrl.contains("/them/"),
            "[FAIL] Không redirect về trang danh sách. URL: " + currentUrl
        );

        System.out.println("✓ TC_02 PASS: Thêm đơn nhập thành công, URL = " + currentUrl);
    }

    /**
     * TC_03 – Tìm kiếm NCC theo tên – có kết quả

     * Lấy tên NCC đầu tiên từ dropdown, dùng 3 ký tự đầu làm từ khóa.
     * Đảm bảo test chạy đúng dù DB thay đổi.
     */
    @Test(description = "TC_03 - Tìm kiếm NCC theo tên – có kết quả")
    public void TC_03_SearchSupplierByName_Found() {
        System.out.println("=== TC_03: Tìm kiếm NCC theo tên – có kết quả ===");

        Assert.assertTrue(page.isAt(), "[FAIL] Không hiển thị trang Thêm mới đơn nhập");

        // Đọc tên NCC đầu tiên từ JS variable danhSachNCC (không mở dropdown)
        String firstSupplierName = page.getFirstNccNameFromJS();
        Assert.assertNotNull(firstSupplierName,
            "[SKIP] Không có NCC nào trong hệ thống");

        // Dùng 3 ký tự đầu làm từ khóa
        String keyword = firstSupplierName.substring(0, Math.min(3, firstSupplierName.length()));
        System.out.println("  → Tên NCC: '" + firstSupplierName + "', từ khóa: '" + keyword + "'");

        // Gõ từ khóa → dropdown hiện 1 lần duy nhất
        page.searchSupplier(keyword);

        Assert.assertTrue(page.isSupplierDropdownVisible(),
            "[FAIL] Dropdown NCC không hiển thị sau khi gõ từ khóa");
        Assert.assertTrue(page.isSupplierInDropdown(keyword),
            "[FAIL] Dropdown không chứa NCC có tên chứa '" + keyword + "'");
        Assert.assertFalse(page.isSupplierNotFoundMessageDisplayed(),
            "[FAIL] Hệ thống hiển thị 'Không tìm thấy NCC' dù NCC tồn tại");

        System.out.println("✓ TC_03 PASS: Dropdown hiển thị NCC có tên chứa '" + keyword + "'");
    }

    @Test(description = "TC_04 - Tìm kiếm NCC theo SĐT – có kết quả")
    public void TC_04_SearchSupplierByPhone_Found() {
        System.out.println("=== TC_04: Tìm kiếm NCC theo SĐT – có kết quả ===");

        Assert.assertTrue(page.isAt(), "[FAIL] Không hiển thị trang Thêm mới đơn nhập");

        // Đọc SĐT NCC đầu tiên từ JS variable danhSachNCC (không mở dropdown)
        String firstSupplierPhone = page.getFirstNccPhoneFromJS();
        Assert.assertNotNull(firstSupplierPhone,
            "[SKIP] Không có NCC nào trong hệ thống");

        // Dùng 4 số cuối làm từ khóa
        String keyword = firstSupplierPhone.substring(Math.max(0, firstSupplierPhone.length() - 4));
        System.out.println("  → SĐT NCC: '" + firstSupplierPhone + "', từ khóa: '" + keyword + "'");

        // Gõ từ khóa → dropdown hiện 1 lần duy nhất
        page.searchSupplier(keyword);

        Assert.assertTrue(page.isSupplierDropdownVisible(),
            "[FAIL] Dropdown NCC không hiển thị sau khi nhập SĐT");
        Assert.assertTrue(page.isSupplierInDropdown(keyword),
            "[FAIL] Dropdown không chứa NCC có SĐT chứa '" + keyword + "'");
        Assert.assertFalse(page.isSupplierNotFoundMessageDisplayed(),
            "[FAIL] Hệ thống hiển thị 'Không tìm thấy NCC' dù SĐT tồn tại");

        System.out.println("✓ TC_04 PASS: Dropdown hiển thị NCC có SĐT chứa '" + keyword + "'");
    }

    /**
     * TC_05 – Tìm kiếm NCC – không có kết quả
     */
    @Test(description = "TC_05 - Tìm kiếm NCC – không có kết quả")
    public void TC_05_SearchSupplier_NotFound() {
        System.out.println("=== TC_05: Tìm kiếm NCC – không có kết quả ===");

        Assert.assertTrue(page.isAt(), "[FAIL] Không hiển thị trang Thêm mới đơn nhập");

        page.searchSupplier(NON_EXISTING_SUPPLIER);
        System.out.println("  → Từ khóa không tồn tại: " + NON_EXISTING_SUPPLIER);

        Assert.assertTrue(page.isSupplierNotFoundMessageDisplayed(),
            "[FAIL] Không hiển thị 'Không tìm thấy NCC'");

        Assert.assertTrue(page.isAddNewSupplierButtonDisplayed(),
            "[FAIL] Không hiển thị nút 'Thêm mới nhà cung cấp'");

        System.out.println("✓ TC_05 PASS: Hiển thị 'Không tìm thấy NCC' và nút 'Thêm mới nhà cung cấp'");
    }

    // ===================== HELPER =====================

    private void sleep(long ms) {
        try { Thread.sleep(ms); } catch (InterruptedException ignored) { }
    }

    /**
     * TC_06 – Chọn NCC từ danh sách – hiển thị thông tin
     * Kết quả: Card NCC hiển thị tên/mã/SĐT/địa chỉ, dropdown đóng lại
     */
    @Test(description = "TC_06 - Chọn NCC từ danh sách – hiển thị thông tin")
    public void TC_06_SelectSupplier_ShowCard() {
        System.out.println("=== TC_06: Chọn NCC từ danh sách – hiển thị thông tin ===");
        Assert.assertTrue(page.isAt(), "[FAIL] Không hiển thị trang");

        // Gõ tên NCC lấy từ JS
        String nccName = page.getFirstNccNameFromJS();
        Assert.assertNotNull(nccName, "[SKIP] Không có NCC trong hệ thống");
        page.searchSupplier(nccName.substring(0, Math.min(3, nccName.length())));

        // Chọn NCC đầu tiên
        page.selectFirstSupplierFromDropdown();

        // Card phải hiển thị
        Assert.assertTrue(page.isSupplierSelected(),
            "[FAIL] Card NCC không hiển thị sau khi chọn");

        // Card phải chứa tên NCC
        String cardText = page.getNccCardText();
        Assert.assertTrue(cardText.toLowerCase().contains(nccName.substring(0,3).toLowerCase()),
            "[FAIL] Card không chứa tên NCC. Card text: " + cardText);

        // Dropdown phải đóng lại
        Assert.assertTrue(page.isSupplierDropdownClosed(),
            "[FAIL] Dropdown NCC không đóng sau khi chọn");

        System.out.println("✓ TC_06 PASS: Card NCC hiển thị, dropdown đóng. Card: " + cardText);
    }

    /**
     * TC_07 – Bỏ chọn NCC đã chọn
     * Kết quả: Card biến mất, ô tìm kiếm trống, có thể tìm kiếm lại
     */
    @Test(description = "TC_07 - Bỏ chọn NCC đã chọn")
    public void TC_07_RemoveSelectedSupplier() {
        System.out.println("=== TC_07: Bỏ chọn NCC đã chọn ===");
        Assert.assertTrue(page.isAt(), "[FAIL] Không hiển thị trang");

        // Chọn NCC trước
        page.openSupplierDropdown();
        page.selectFirstSupplierFromDropdown();
        Assert.assertTrue(page.isSupplierSelected(), "[FAIL] Chưa chọn được NCC");

        // Nhấn × để bỏ chọn
        page.clickRemoveNccCard();

        // Card phải biến mất
        Assert.assertFalse(page.isSupplierSelected(),
            "[FAIL] Card NCC vẫn hiển thị sau khi nhấn ×");

        // Ô tìm kiếm phải trống
        Assert.assertEquals(page.getSupplierSearchValue(), "",
            "[FAIL] Ô tìm kiếm NCC không trống sau khi bỏ chọn");

        // Có thể tìm kiếm lại (ô không bị disabled)
        page.openSupplierDropdown();
        Assert.assertTrue(page.isSupplierDropdownVisible(),
            "[FAIL] Không thể tìm kiếm lại sau khi bỏ chọn NCC");

        System.out.println("✓ TC_07 PASS: Card biến mất, ô trống, tìm kiếm lại được");
    }

    /**
     * TC_08 – Tìm kiếm sản phẩm theo tên – có kết quả
     * Kết quả: Dropdown hiển thị SP có tên khớp từ khóa (kèm mã hàng)
     */
    @Test(description = "TC_08 - Tìm kiếm sản phẩm theo tên – có kết quả")
    public void TC_08_SearchProduct_Found() {
        System.out.println("=== TC_08: Tìm kiếm sản phẩm theo tên – có kết quả ===");
        Assert.assertTrue(page.isAt(), "[FAIL] Không hiển thị trang");

        // Lấy tên SP đầu tiên từ JS
        String spName = page.getFirstSpNameFromJS();
        Assert.assertNotNull(spName, "[SKIP] Không có sản phẩm trong hệ thống");

        String keyword = spName.substring(0, Math.min(3, spName.length()));
        System.out.println("  → Từ khóa SP: '" + keyword + "'");

        page.searchProduct(keyword);

        Assert.assertTrue(page.isProductDropdownVisible(),
            "[FAIL] Dropdown SP không hiển thị");
        Assert.assertTrue(page.isProductInDropdown(keyword),
            "[FAIL] Dropdown không chứa SP có tên '" + keyword + "'");
        // Dropdown phải kèm mã hàng (text "Mã hàng hóa:")
        Assert.assertTrue(page.isProductInDropdown("Mã hàng hóa"),
            "[FAIL] Dropdown không hiển thị mã hàng hóa");
        Assert.assertFalse(page.isProductNotFoundMessageDisplayed(),
            "[FAIL] Hiển thị 'Không tìm thấy sản phẩm' dù SP tồn tại");

        System.out.println("✓ TC_08 PASS: Dropdown hiển thị SP có tên '" + keyword + "' kèm mã hàng");
    }

    /**
     * TC_09 – Tìm kiếm sản phẩm – không có kết quả
     * Kết quả: Dropdown hiển thị "Không tìm thấy sản phẩm" và nút "Thêm mới hàng hóa"
     */
    @Test(description = "TC_09 - Tìm kiếm sản phẩm – không có kết quả")
    public void TC_09_SearchProduct_NotFound() {
        System.out.println("=== TC_09: Tìm kiếm sản phẩm – không có kết quả ===");
        Assert.assertTrue(page.isAt(), "[FAIL] Không hiển thị trang");

        page.searchProduct("XYZ_SP_KHONG_TON_TAI_999");

        Assert.assertTrue(page.isProductNotFoundMessageDisplayed(),
            "[FAIL] Không hiển thị 'Không tìm thấy sản phẩm'");
        Assert.assertTrue(page.isAddNewProductButtonDisplayed(),
            "[FAIL] Không hiển thị nút 'Thêm mới hàng hóa'");

        System.out.println("✓ TC_09 PASS: Hiển thị 'Không tìm thấy sản phẩm' và nút 'Thêm mới hàng hóa'");
    }

    /**
     * TC_10 – Chọn sản phẩm từ danh sách – hiển thị vào bảng
     * Kết quả: SP vào bảng với SL=1, đơn giá tự động điền, chiết khấu=0
     */
    @Test(description = "TC_10 - Chọn sản phẩm từ danh sách – hiển thị vào bảng")
    public void TC_10_SelectProduct_AddToTable() {
        System.out.println("=== TC_10: Chọn sản phẩm từ danh sách – hiển thị vào bảng ===");
        Assert.assertTrue(page.isAt(), "[FAIL] Không hiển thị trang");

        // Lấy đơn giá SP đầu tiên từ JS để so sánh
        double expectedDonGia = page.getFirstSpDonGiaFromJS();

        page.openProductDropdown();
        page.selectFirstProductFromDropdown();
        sleep(500);

        // Bảng phải hiển thị
        Assert.assertTrue(page.isProductTableVisible(),
            "[FAIL] Bảng sản phẩm không hiển thị sau khi chọn SP");

        // Số dòng = 1
        Assert.assertEquals(page.getProductRowCount(), 1,
            "[FAIL] Bảng không có đúng 1 dòng sản phẩm");

        // Số lượng mặc định = 1
        Assert.assertEquals(page.getProductQuantityInTable(0), "1",
            "[FAIL] Số lượng mặc định không phải 1");

        // Chiết khấu mặc định = 0
        Assert.assertEquals(page.getProductChietKhauInTable(0), "0",
            "[FAIL] Chiết khấu mặc định không phải 0");

        // Đơn giá phải được tự động điền (không rỗng và không phải 0)
        String donGiaText = page.getProductDonGiaInTable(0);
        Assert.assertFalse(donGiaText.isEmpty(),
            "[FAIL] Đơn giá không được tự động điền");

        System.out.println("✓ TC_10 PASS: SP vào bảng, SL=1, đơn giá=" + donGiaText + ", CK=0");
    }

    /**
     * TC_11 – Chọn sản phẩm đã có trong bảng
     * Kết quả: SP không bị thêm trùng, bảng vẫn chỉ có 1 dòng
     */
    @Test(description = "TC_11 - Chọn sản phẩm đã có trong bảng")
    public void TC_11_SelectDuplicateProduct_NoNewRow() {
        System.out.println("=== TC_11: Chọn sản phẩm đã có trong bảng ===");
        Assert.assertTrue(page.isAt(), "[FAIL] Không hiển thị trang");

        // Chọn SP lần 1
        page.openProductDropdown();
        page.selectFirstProductFromDropdown();
        sleep(500);
        Assert.assertEquals(page.getProductRowCount(), 1, "[FAIL] Lần 1 không có 1 dòng");

        // Chọn lại SP đó lần 2
        page.openProductDropdown();
        page.selectFirstProductFromDropdown();
        sleep(500);

        // Vẫn chỉ có 1 dòng (không bị thêm trùng)
        Assert.assertEquals(page.getProductRowCount(), 1,
            "[FAIL] SP bị thêm trùng – bảng có nhiều hơn 1 dòng");

        System.out.println("✓ TC_11 PASS: SP không bị thêm trùng, bảng vẫn 1 dòng");
    }

    /**
     * TC_12 – Nhập số lượng hợp lệ
     * Kết quả: Thành tiền = đơn giá × 10, tổng tiền cập nhật theo
     */
    @Test(description = "TC_12 - Nhập số lượng hợp lệ")
    public void TC_12_UpdateQuantity_RecalculateTotal() {
        System.out.println("=== TC_12: Nhập số lượng hợp lệ ===");
        Assert.assertTrue(page.isAt(), "[FAIL] Không hiển thị trang");

        // Chọn SP vào bảng
        page.openProductDropdown();
        page.selectFirstProductFromDropdown();
        sleep(500);

        // Lấy đơn giá hiện tại từ bảng (do hệ thống tự điền)
        String donGiaRaw = page.getProductDonGiaInTable(0);
        System.out.println("  → Đơn giá tự điền: " + donGiaRaw);

        // Sửa số lượng = 10
        page.setProductQuantity(0, "10");
        sleep(500);

        // Tính thành tiền mong đợi = đơn giá × 10
        // Lấy đơn giá số từ JS (chính xác hơn)
        double donGia = page.getFirstSpDonGiaFromJS();
        long expectedThanhTien = (long)(donGia * 10);
        System.out.println("  → Đơn giá: " + donGia + ", SL: 10, Thành tiền mong đợi: " + expectedThanhTien);

        String thanhTien = page.getProductThanhTienInTable(0);
        Assert.assertEquals(thanhTien, String.valueOf(expectedThanhTien),
            "[FAIL] Thành tiền không đúng. Mong đợi: " + expectedThanhTien + ", Thực tế: " + thanhTien);

        // Tổng tiền phải bằng thành tiền (chỉ có 1 SP)
        String tongTien = page.getTongTienDisplay();
        Assert.assertEquals(tongTien, String.valueOf(expectedThanhTien),
            "[FAIL] Tổng tiền không cập nhật. Thực tế: " + tongTien);

        System.out.println("✓ TC_12 PASS: Thành tiền = " + expectedThanhTien + "đ, tổng tiền cập nhật đúng");
    }

    /**
     * TC_13 – Nhập số lượng = 0
     * Kết quả: Hệ thống không lưu, hiển thị thông báo lỗi
     */
    @Test(description = "TC_13 - Nhập số lượng = 0")
    public void TC_13_QuantityZero_ShowError() {
        System.out.println("=== TC_13: Nhập số lượng = 0 ===");
        Assert.assertTrue(page.isAt(), "[FAIL] Không hiển thị trang");

        // Nhập ngày, chọn NCC, chọn SP
        String now = java.time.LocalDateTime.now()
            .format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm"));
        page.enterImportDate(now);
        page.openSupplierDropdown();
        page.selectFirstSupplierFromDropdown();
        page.openProductDropdown();
        page.selectFirstProductFromDropdown();
        sleep(500);

        // Sửa số lượng = 0
        page.setProductQuantity(0, "0");

        // Submit
        page.clickSubmit();

        // Phải vẫn ở trang /them/ (không redirect)
        String url = page.getCurrentUrl();
        Assert.assertTrue(url.contains("/them/"),
            "[FAIL] Hệ thống cho phép lưu với số lượng = 0. URL: " + url);

        System.out.println("✓ TC_13 PASS: Hệ thống không lưu khi số lượng = 0");
    }

    /**
     * TC_14 – Kiểm tra tính thành tiền (có chiết khấu)
     * Công thức: 100.000 × 5 × (1 - 10/100) = 450.000đ
     */
    @Test(description = "TC_14 - Kiểm tra tính thành tiền có chiết khấu")
    public void TC_14_CalcThanhTien_WithDiscount() {
        System.out.println("=== TC_14: Kiểm tra tính thành tiền (có chiết khấu) ===");
        Assert.assertTrue(page.isAt(), "[FAIL] Không hiển thị trang");

        page.openProductDropdown();
        page.selectFirstProductFromDropdown();
        sleep(500);

        // Nhập đơn giá=100000, SL=5, CK=10
        page.setProductDonGia(0, "100000");
        page.setProductQuantity(0, "5");
        page.setProductChietKhau(0, "10");
        sleep(500);

        // Thành tiền = 100000 × 5 × (1 - 10/100) = 450000
        String thanhTien = page.getProductThanhTienInTable(0);
        Assert.assertEquals(thanhTien, "450000",
            "[FAIL] Thành tiền sai. Mong đợi: 450000, Thực tế: " + thanhTien);

        System.out.println("✓ TC_14 PASS: Thành tiền = 450.000đ (đúng công thức)");
    }

    /**
     * TC_15 – Kiểm tra tổng tiền nhiều sản phẩm
     * SP1: 450.000đ + SP2: 150.000đ = 600.000đ
     */
    @Test(description = "TC_15 - Kiểm tra tổng tiền nhiều sản phẩm")
    public void TC_15_TotalAmount_MultipleProducts() {
        System.out.println("=== TC_15: Kiểm tra tổng tiền nhiều sản phẩm ===");
        Assert.assertTrue(page.isAt(), "[FAIL] Không hiển thị trang");

        // Cần ít nhất 2 SP trong DB
        String sp1Name = page.getFirstSpNameFromJS();
        Assert.assertNotNull(sp1Name, "[SKIP] Không có SP trong hệ thống");

        // Thêm SP1
        page.openProductDropdown();
        page.selectFirstProductFromDropdown();
        sleep(500);
        page.setProductDonGia(0, "100000");
        page.setProductQuantity(0, "5");
        page.setProductChietKhau(0, "10");
        // SP1 thành tiền = 450.000

        // Thêm SP2 (item thứ 2 trong dropdown)
        By secondItem = By.xpath(
            "//div[@id='spDropdown']//div[contains(@class,'dropdown-item')" +
            " and not(contains(@class,'dropdown-add'))][2]"
        );
        page.openProductDropdown();
        try {
            driver.findElement(secondItem).click();
            sleep(500);
        } catch (Exception e) {
            System.out.println("  [SKIP] Chỉ có 1 SP trong DB – bỏ qua TC_15");
            return;
        }
        page.setProductDonGia(1, "50000");
        page.setProductQuantity(1, "3");
        page.setProductChietKhau(1, "0");
        // SP2 thành tiền = 150.000
        sleep(500);

        // Tổng = 450.000 + 150.000 = 600.000
        String tongTien = page.getTongTienDisplay();
        Assert.assertEquals(tongTien, "600000",
            "[FAIL] Tổng tiền sai. Mong đợi: 600000, Thực tế: " + tongTien);

        // Số lượng HH hiển thị = 5+3 = 8
        String soLuongHH = page.getSoLuongHHDisplay();
        Assert.assertTrue(soLuongHH.contains("8"),
            "[FAIL] Số lượng HH hiển thị sai. Thực tế: " + soLuongHH);

        System.out.println("✓ TC_15 PASS: Tổng tiền = 600.000đ, số lượng HH = 8");
    }

    /**
     * TC_16 – Xóa sản phẩm khỏi bảng
     * Bước: Thêm 2 SP → nhấn × xóa SP đầu tiên
     * Kết quả: Bảng còn 1 dòng, tổng tiền cập nhật lại
     */
    @Test(description = "TC_16 - Xóa sản phẩm khỏi bảng")
    public void TC_16_RemoveProductFromTable() {
        System.out.println("=== TC_16: Xóa sản phẩm khỏi bảng ===");
        Assert.assertTrue(page.isAt(), "[FAIL] Không hiển thị trang");

        page.openProductDropdown();
        page.selectFirstProductFromDropdown();
        sleep(500);

        By secondItem = By.xpath(
            "//div[@id='spDropdown']//div[contains(@class,'dropdown-item')" +
            " and not(contains(@class,'dropdown-add'))][2]"
        );
        page.openProductDropdown();
        try {
            driver.findElement(secondItem).click();
            sleep(500);
        } catch (Exception e) {
            System.out.println("  [SKIP] Chỉ có 1 SP trong DB");
            return;
        }

        Assert.assertEquals(page.getProductRowCount(), 2, "[FAIL] Chưa có 2 dòng SP");

        String tongTienTruoc = page.getTongTienDisplay();
        System.out.println("  → Tổng tiền trước xóa: " + tongTienTruoc);

        page.removeProductFromTable(0);
        sleep(300);

        Assert.assertEquals(page.getProductRowCount(), 1,
            "[FAIL] Bảng không còn đúng 1 dòng sau khi xóa");

        String tongTienSau = page.getTongTienDisplay();
        Assert.assertNotEquals(tongTienSau, tongTienTruoc,
            "[FAIL] Tổng tiền không cập nhật sau khi xóa SP");

        System.out.println("✓ TC_16 PASS: SP bị xóa, bảng còn 1 dòng, tổng tiền cập nhật");
    }

    /**
     * TC_17 – Nhấn "Thêm" khi chưa chọn NCC
     */
    @Test(description = "TC_17 - Nhấn Thêm khi chưa chọn NCC")
    public void TC_17_Submit_WithoutNCC() {
        System.out.println("=== TC_17: Nhấn Thêm khi chưa chọn NCC ===");
        Assert.assertTrue(page.isAt(), "[FAIL] Không hiển thị trang");

        String now = java.time.LocalDateTime.now()
            .format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm"));
        page.enterImportDate(now);
        page.openProductDropdown();
        page.selectFirstProductFromDropdown();
        sleep(300);
        page.clickSubmit();

        Assert.assertTrue(page.isValidationToastVisible(),
            "[FAIL] Không hiển thị toast validation");
        Assert.assertTrue(page.getCurrentUrl().contains("/them/"),
            "[FAIL] Hệ thống redirect dù chưa chọn NCC");

        System.out.println("✓ TC_17 PASS: Toast hiển thị, không lưu hóa đơn");
    }

    /**
     * TC_18 – Nhấn "Thêm" khi chưa chọn sản phẩm
     */
    @Test(description = "TC_18 - Nhấn Thêm khi chưa chọn sản phẩm")
    public void TC_18_Submit_WithoutProduct() {
        System.out.println("=== TC_18: Nhấn Thêm khi chưa chọn sản phẩm ===");
        Assert.assertTrue(page.isAt(), "[FAIL] Không hiển thị trang");

        String now = java.time.LocalDateTime.now()
            .format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm"));
        page.enterImportDate(now);
        page.openSupplierDropdown();
        page.selectFirstSupplierFromDropdown();
        sleep(300);
        page.clickSubmit();

        Assert.assertTrue(page.isValidationToastVisible(),
            "[FAIL] Không hiển thị toast validation");
        Assert.assertTrue(page.getCurrentUrl().contains("/them/"),
            "[FAIL] Hệ thống redirect dù chưa chọn SP");

        System.out.println("✓ TC_18 PASS: Toast hiển thị, không lưu hóa đơn");
    }

    /**
     * TC_19 – Nhấn "Thêm" khi chưa nhập ngày
     */
    @Test(description = "TC_19 - Nhấn Thêm khi chưa nhập ngày")
    public void TC_19_Submit_WithoutDate() {
        System.out.println("=== TC_19: Nhấn Thêm khi chưa nhập ngày ===");
        Assert.assertTrue(page.isAt(), "[FAIL] Không hiển thị trang");

        page.openSupplierDropdown();
        page.selectFirstSupplierFromDropdown();
        sleep(300);
        page.openProductDropdown();
        page.selectFirstProductFromDropdown();
        sleep(300);
        page.clickSubmit();

        Assert.assertTrue(page.isValidationToastVisible(),
            "[FAIL] Không hiển thị toast validation");
        Assert.assertTrue(page.getCurrentUrl().contains("/them/"),
            "[FAIL] Hệ thống redirect dù chưa nhập ngày");

        System.out.println("✓ TC_19 PASS: Toast hiển thị, không lưu hóa đơn");
    }

    /**
     * TC_20 – Nhập ngày lớn hơn ngày hiện tại
     * Kết quả mong đợi: Hệ thống KHÔNG cho phép lưu, hiển thị thông báo lỗi
     * Kết quả thực tế: Hệ thống vẫn lưu được → BUG
     */
    @Test(description = "TC_20 - Nhập ngày lớn hơn ngày hiện tại")
    public void TC_20_FutureDate_Submit() {
        System.out.println("=== TC_20: Nhập ngày lớn hơn ngày hiện tại ===");
        Assert.assertTrue(page.isAt(), "[FAIL] Không hiển thị trang");

        String futureDate = java.time.LocalDateTime.now().plusDays(1)
            .format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm"));
        page.enterImportDate(futureDate);
        System.out.println("  → Ngày tương lai: " + futureDate);

        page.openSupplierDropdown();
        page.selectFirstSupplierFromDropdown();
        sleep(300);
        page.openProductDropdown();
        page.selectFirstProductFromDropdown();
        sleep(300);
        page.clickSubmit();

        String url = page.getCurrentUrl();
        System.out.println("  → URL sau submit: " + url);

        // Kết quả mong đợi: vẫn ở /them/ vì ngày tương lai không hợp lệ
        Assert.assertTrue(url.contains("/them/"),
            "[BUG] Hệ thống cho phép lưu hóa đơn với ngày nhập > ngày hiện tại. URL: " + url
        );

        System.out.println("✓ TC_20 PASS: Hệ thống từ chối ngày tương lai");
    }

    /**
     * TC_21 – Nhấn "Hủy"
     */
    @Test(description = "TC_21 - Nhấn Hủy")
    public void TC_21_Cancel_RedirectToList() {
        System.out.println("=== TC_21: Nhấn Hủy ===");
        Assert.assertTrue(page.isAt(), "[FAIL] Không hiển thị trang");

        String now = java.time.LocalDateTime.now()
            .format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm"));
        page.enterImportDate(now);
        page.openSupplierDropdown();
        page.selectFirstSupplierFromDropdown();
        sleep(300);
        page.clickCancel();
        sleep(1000);

        String url = page.getCurrentUrl();
        Assert.assertTrue(
            url.contains("/nhap-hang/") && !url.contains("/them/"),
            "[FAIL] Không chuyển về trang danh sách. URL: " + url
        );

        System.out.println("✓ TC_21 PASS: Chuyển về /nhap-hang/. URL: " + url);
    }
}
